"""Deterministic stdlib JSON-LD emitter (Run F — jsonld-emitter, R6).

Serializes the two machine-complete CT6 sidecars —

* ``docs/data-dictionary.json`` (the catalog: tables + fields + provenance), and
* ``lineage-graph.json`` (the lineage: ``function`` / ``endpoint`` / ``data_asset``
  nodes joined by ``reads`` / ``writes`` / ``calls`` / ... edges)

— as **JSON-LD** for the external catalog / lineage ecosystems that Stage 6 of the
``data-engineering-exploration`` skill names (OpenLineage / Marquez / DataHub /
dbt). JSON-LD is just JSON with an ``@context``, so this is pure stdlib ``json``:
NO ``rdflib``, NO ``pyld`` (F-D1).

Shape mapping (F-D2):

* a dictionary table  -> a ``schema:Dataset`` (a ``dcat:Catalog`` wraps them);
  each field           -> a ``schema:variableMeasured`` ``schema:PropertyValue``
  carrying ``schema:propertyID`` = the field name, ``schema:description`` = the
  definition, and ``ct6:provenance`` / ``ct6:confidence`` for the CT6 fidelity
  metadata that has no standard term. A table's measured ``usage`` block (Run E)
  rides its Dataset node as ``ct6:usage`` (it is a table-level measure — attaching
  it once to the Dataset, not duplicating it onto every field);
* a lineage ``data_asset`` node -> a ``prov:Entity``; a ``function`` / ``endpoint``
  node -> a ``prov:Activity``; a ``reads`` edge -> the activity ``prov:used`` the
  entity; a ``writes`` edge -> the entity ``prov:wasGeneratedBy`` the activity.
  ``calls`` / ``serves`` / ``serves_route`` / ``modifies`` / ``originates`` ride
  documented ``prov`` / ``ct6`` relations.

Two disciplines are load-bearing and tested:

* **Walk only what exists (F-D4).** Only edges present in the graph are emitted;
  an unknown edge kind is skipped-with-note, never invented; an edge whose
  endpoint is not a declared node is skipped (referential closure is preserved,
  the ghost node is never fabricated). An empty / absent input yields an empty but
  VALID ``@graph`` — no invented triples. Provenance / confidence travel verbatim.
* **Structural validity is the correctness bar (F-D3).** ``validate_jsonld``
  asserts a resolvable ``@context``, every node an ``@id`` + ``@type``, unique
  ``@id``s, and referential closure (every referenced ``@id`` resolves to a node).
  A round-trip (``json.dumps`` -> ``json.loads``) proves no loss / no fabrication.

HONEST BOUNDARY: the emitter is verified against the schema.org / DCAT / PROV-O
SHAPES (structural validation + round-trip). NO live external-consumer ingestion
(OpenLineage / Marquez / DataHub) is verified, and none is wired — a downstream
consumer, when one is adopted, points at this output.

The node/edge vocabulary is single-sourced from ``hooks/lineage_graph.py``
(``NODE_KINDS`` / ``EDGE_KINDS``); a drift test pins ``_NODE_TYPE`` / ``_EDGE_MAP``
to it so the emitter recognizes exactly the kinds the graph admits.

CLI::

    python jsonld_export.py export-jsonld [--dictionary <json>] [--graph <json>]
                                          [--out <path>] [--validate] [--notes]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Iterable, Optional

# --------------------------------------------------------------------------- #
# The @context — real vocabulary URLs (F-D1). ``ct6`` is the CT6 term base for
# the provenance / confidence / usage annotations that have no standard term.
# --------------------------------------------------------------------------- #
CONTEXT: dict[str, str] = {
    "schema": "https://schema.org/",
    "dcat": "http://www.w3.org/ns/dcat#",
    "prov": "http://www.w3.org/ns/prov#",
    "ct6": "https://ct6.dev/ns#",
}

# Node kind -> JSON-LD @type (F-D2). Keys are pinned to lineage_graph.NODE_KINDS.
_NODE_TYPE: dict[str, str] = {
    "data_asset": "prov:Entity",
    "function": "prov:Activity",
    "endpoint": "prov:Activity",
}

# Edge kind -> (attach_on, predicate, target): the relation is attached to the
# ``attach_on`` endpoint's node and references the ``target`` endpoint by @id.
# Keys are pinned to lineage_graph.EDGE_KINDS (a drift test enforces it), so an
# edge kind the graph admits is always mapped and an unknown kind is skipped.
_EDGE_MAP: dict[str, tuple[str, str, str]] = {
    "reads": ("src", "prov:used", "dst"),          # activity used entity
    "writes": ("dst", "prov:wasGeneratedBy", "src"),  # entity generated by activity
    "modifies": ("dst", "prov:wasGeneratedBy", "src"),  # modified entity re-generated
    "calls": ("src", "ct6:calls", "dst"),          # activity calls activity
    "serves": ("src", "ct6:serves", "dst"),        # activity serves entity/activity
    "serves_route": ("src", "ct6:servesRoute", "dst"),  # FE->BE route match
    "originates": ("src", "ct6:originates", "dst"),
}


# --------------------------------------------------------------------------- #
# Reference walking + validation (F-D3)
# --------------------------------------------------------------------------- #
def _iter_refs(value: Any) -> list[str]:
    """Return every ``@id`` referenced (as a ``{"@id": ...}`` marker) inside a
    property value, recursing through nested lists/dicts. A node's own ``@id``
    string is never passed here (only property values are), so this yields only
    references, not node identities."""
    out: list[str] = []
    if isinstance(value, dict):
        rid = value.get("@id")
        if isinstance(rid, str):
            out.append(rid)
        for key, sub in value.items():
            if key == "@id":
                continue
            out.extend(_iter_refs(sub))
    elif isinstance(value, list):
        for item in value:
            out.extend(_iter_refs(item))
    return out


def _collect_references(graph: list[dict[str, Any]]) -> list[str]:
    """Every referenced ``@id`` across all node property values (excluding each
    node's own ``@id`` / ``@type``)."""
    refs: list[str] = []
    for node in graph:
        if not isinstance(node, dict):
            continue
        for key, value in node.items():
            if key in ("@id", "@type"):
                continue
            refs.extend(_iter_refs(value))
    return refs


def validate_jsonld(doc: Any) -> list[str]:
    """Structurally validate a JSON-LD document; return a list of error strings
    (empty == valid). Checks (F-D3): a resolvable ``@context`` (a mapping or a
    list), a list ``@graph``, every node a non-empty string ``@id`` + a truthy
    ``@type``, ``@id``s unique, and referential closure — every referenced ``@id``
    (edge endpoints, ``variableMeasured`` / ``dcat:dataset`` refs) resolves to a
    declared node."""
    errors: list[str] = []
    if not isinstance(doc, dict):
        return [f"document is not a JSON object (got {type(doc).__name__})"]

    ctx = doc.get("@context")
    if not isinstance(ctx, (dict, list)):
        errors.append("@context missing or not a resolvable mapping/list")

    graph = doc.get("@graph")
    if not isinstance(graph, list):
        errors.append("@graph missing or not a list")
        return errors

    node_ids: set[str] = set()
    for i, node in enumerate(graph):
        if not isinstance(node, dict):
            errors.append(f"@graph[{i}] is not an object (got {type(node).__name__})")
            continue
        nid = node.get("@id")
        if not isinstance(nid, str) or not nid.strip():
            errors.append(f"@graph[{i}] missing a non-empty string @id")
        else:
            if nid in node_ids:
                errors.append(f"duplicate @id {nid!r}")
            node_ids.add(nid)
        if not node.get("@type"):
            errors.append(f"@graph[{i}] (@id={nid!r}) missing @type")

    for ref in _collect_references(graph):
        if ref not in node_ids:
            errors.append(f"referenced @id {ref!r} does not resolve to a node")
    return errors


# --------------------------------------------------------------------------- #
# Dictionary -> schema.org / DCAT (F-D2)
# --------------------------------------------------------------------------- #
def _iter_fields(
    tinfo: dict[str, Any], table: str, notes: list[str]
) -> Iterable[tuple[str, dict[str, Any]]]:
    """Yield ``(field_name, field_info)`` for a table entry, handling BOTH the
    engine's list-of-field-dicts shape (each with a ``field`` key) and a
    field-name-keyed mapping shape. A list entry lacking a ``field`` name is
    skipped-with-note rather than guessed."""
    fields = tinfo.get("fields")
    if isinstance(fields, dict):
        for name, info in fields.items():
            yield str(name), dict(info) if isinstance(info, dict) else {}
    elif isinstance(fields, list):
        for info in fields:
            if not isinstance(info, dict):
                notes.append(f"skipped a field of table {table!r}: not a mapping")
                continue
            name = info.get("field")
            if name is None:
                notes.append(f"skipped a field of table {table!r}: no 'field' name")
                continue
            yield str(name), info


def _build_dictionary_graph(
    dict_json: Optional[dict[str, Any]]
) -> tuple[list[dict[str, Any]], list[str]]:
    """Build the ``@graph`` node list for a data-dictionary sidecar (+ notes)."""
    nodes: list[dict[str, Any]] = []
    notes: list[str] = []
    tables = (dict_json or {}).get("tables") or {}
    if not isinstance(tables, dict) or not tables:
        return nodes, notes

    dataset_refs: list[dict[str, str]] = []
    for table, tinfo in tables.items():
        if not isinstance(tinfo, dict):
            notes.append(f"skipped table {table!r}: not a mapping")
            continue
        dataset_id = f"ct6:dataset/{table}"
        field_refs: list[dict[str, str]] = []
        for name, info in _iter_fields(tinfo, str(table), notes):
            field_id = f"ct6:field/{table}/{name}"
            pv: dict[str, Any] = {
                "@id": field_id,
                "@type": "schema:PropertyValue",
                "schema:propertyID": name,
            }
            # definition / provenance / confidence PRESERVED VERBATIM — emit only
            # what the sidecar carries (no fabricated defaults).
            if info.get("definition") is not None:
                pv["schema:description"] = info["definition"]
            if info.get("provenance") is not None:
                pv["ct6:provenance"] = info["provenance"]
            if info.get("confidence") is not None:
                pv["ct6:confidence"] = info["confidence"]
            if info.get("type") is not None:
                pv["ct6:fieldType"] = info["type"]
            nodes.append(pv)
            field_refs.append({"@id": field_id})

        dataset: dict[str, Any] = {
            "@id": dataset_id,
            "@type": "schema:Dataset",
            "schema:name": table,
            "schema:variableMeasured": field_refs,
        }
        usage = tinfo.get("usage")
        if isinstance(usage, dict) and usage:
            dataset["ct6:usage"] = dict(usage)  # table-level measure, verbatim
        nodes.append(dataset)
        dataset_refs.append({"@id": dataset_id})

    if dataset_refs:
        # a dcat:Catalog wraps the datasets (only when >= 1 exists — an empty
        # catalog would be a fabricated node).
        nodes.insert(0, {
            "@id": "ct6:catalog",
            "@type": "dcat:Catalog",
            "dcat:dataset": dataset_refs,
        })
    return nodes, notes


# --------------------------------------------------------------------------- #
# Lineage -> PROV-O (F-D2)
# --------------------------------------------------------------------------- #
def _build_lineage_graph(
    graph_json: Optional[dict[str, Any]]
) -> tuple[list[dict[str, Any]], list[str]]:
    """Build the ``@graph`` node list for a lineage-graph sidecar (+ notes).

    Two passes: build the prov nodes (skipping an unknown node kind), then walk
    ONLY the edges present in the graph — an unknown edge kind or an edge with a
    non-declared endpoint is skipped-with-note, never invented."""
    nodes: list[dict[str, Any]] = []
    notes: list[str] = []
    raw_nodes = (graph_json or {}).get("nodes") or []
    raw_edges = (graph_json or {}).get("edges") or []

    by_id: dict[str, dict[str, Any]] = {}
    for n in raw_nodes:
        if not isinstance(n, dict):
            notes.append("skipped a node: not a mapping")
            continue
        nid = n.get("id")
        kind = n.get("kind")
        if not isinstance(nid, str) or not nid.strip():
            notes.append(f"skipped a node with a missing id (kind={kind!r})")
            continue
        jtype = _NODE_TYPE.get(kind)
        if jtype is None:
            notes.append(f"skipped node {nid!r}: unknown node kind {kind!r}")
            continue
        node: dict[str, Any] = {"@id": nid, "@type": jtype, "ct6:nodeKind": kind}
        if n.get("name") is not None:
            node["schema:name"] = n["name"]
        if n.get("path") is not None:
            node["ct6:path"] = n["path"]
        by_id[nid] = node
        nodes.append(node)

    for e in raw_edges:
        if not isinstance(e, dict):
            notes.append("skipped an edge: not a mapping")
            continue
        src = e.get("src")
        dst = e.get("dst")
        kind = e.get("kind")
        mapping = _EDGE_MAP.get(kind)
        if mapping is None:
            notes.append(f"skipped edge {src!r}->{dst!r}: unknown edge kind {kind!r}")
            continue
        if src not in by_id or dst not in by_id:
            notes.append(
                f"skipped {kind} edge {src!r}->{dst!r}: an endpoint is not a declared node"
            )
            continue
        attach_on, predicate, target = mapping
        host = by_id[src] if attach_on == "src" else by_id[dst]
        ref_id = dst if target == "dst" else src
        host.setdefault(predicate, []).append({"@id": ref_id})
    return nodes, notes


# --------------------------------------------------------------------------- #
# Public API
# --------------------------------------------------------------------------- #
def _doc(nodes: list[dict[str, Any]]) -> dict[str, Any]:
    return {"@context": dict(CONTEXT), "@graph": nodes}


def export_dictionary_jsonld(dict_json: Optional[dict[str, Any]]) -> dict[str, Any]:
    """Serialize a data-dictionary sidecar as a JSON-LD document (schema.org/DCAT)."""
    return _doc(_build_dictionary_graph(dict_json)[0])


def export_lineage_jsonld(graph_json: Optional[dict[str, Any]]) -> dict[str, Any]:
    """Serialize a lineage-graph sidecar as a JSON-LD document (PROV-O)."""
    return _doc(_build_lineage_graph(graph_json)[0])


def export_combined(
    dict_json: Optional[dict[str, Any]] = None,
    graph_json: Optional[dict[str, Any]] = None,
) -> dict[str, Any]:
    """Serialize BOTH sidecars as one JSON-LD document (``@context`` + ``@graph``)."""
    nodes = _build_dictionary_graph(dict_json)[0] + _build_lineage_graph(graph_json)[0]
    return _doc(nodes)


def export_notes(graph_json: Optional[dict[str, Any]]) -> list[str]:
    """Return the skip notes for a lineage-graph sidecar (unknown edge kinds,
    non-declared endpoints, unknown node kinds) — the honest record of what was
    NOT emitted."""
    return _build_lineage_graph(graph_json)[1]


def all_notes(
    dict_json: Optional[dict[str, Any]] = None,
    graph_json: Optional[dict[str, Any]] = None,
) -> list[str]:
    """Skip notes across both sidecars."""
    return _build_dictionary_graph(dict_json)[1] + _build_lineage_graph(graph_json)[1]


def roundtrip(doc: dict[str, Any]) -> dict[str, Any]:
    """Serialize with stdlib ``json`` and re-parse. JSON-LD is plain JSON, so a
    faithful emitter round-trips value-for-value (``roundtrip(doc) == doc``);
    this is the honest substitute for a live-consumer ingestion check."""
    return json.loads(json.dumps(doc, ensure_ascii=False))


def nodes_by_type(doc: dict[str, Any], type_: str) -> list[dict[str, Any]]:
    """Every ``@graph`` node whose ``@type`` equals ``type_``."""
    return [n for n in doc.get("@graph", []) if isinstance(n, dict) and n.get("@type") == type_]


def node_by_id(doc: dict[str, Any], node_id: str) -> Optional[dict[str, Any]]:
    """The ``@graph`` node with ``@id`` == ``node_id`` (or ``None``)."""
    for n in doc.get("@graph", []):
        if isinstance(n, dict) and n.get("@id") == node_id:
            return n
    return None


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #
def _load_json(path: Optional[str]) -> dict[str, Any]:
    """Load a sidecar JSON file; an absent / malformed / non-object path yields
    ``{}`` so an absent sidecar becomes an empty (but valid) ``@graph``, never a
    crash and never a fabricated node."""
    if not path:
        return {}
    p = Path(path)
    if not p.exists():
        return {}
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError, UnicodeDecodeError):
        return {}
    return data if isinstance(data, dict) else {}


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(prog="jsonld_export", description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    ex = sub.add_parser(
        "export-jsonld",
        help="emit the data-dictionary + lineage-graph sidecars as one JSON-LD document",
    )
    ex.add_argument("--dictionary", help="path to a data-dictionary.json sidecar")
    ex.add_argument("--graph", help="path to a lineage-graph.json sidecar")
    ex.add_argument("--out", help="write the JSON-LD here (default: stdout)")
    ex.add_argument("--validate", action="store_true", help="only report validity, emit nothing")
    ex.add_argument("--notes", action="store_true", help="print skip notes to stderr")
    args = parser.parse_args(argv)

    if args.command == "export-jsonld":
        dict_json = _load_json(args.dictionary)
        graph_json = _load_json(args.graph)
        doc = export_combined(dict_json, graph_json)
        errors = validate_jsonld(doc)
        if args.notes:
            for note in all_notes(dict_json, graph_json):
                print(f"NOTE: {note}", file=sys.stderr)
        if args.validate:
            for e in errors:
                print(f"INVALID: {e}", file=sys.stderr)
            print(f"{'VALID' if not errors else 'INVALID'} "
                  f"({len(doc['@graph'])} node(s))")
            return 0 if not errors else 1
        text = json.dumps(doc, indent=2, ensure_ascii=False)
        if args.out:
            Path(args.out).write_text(text, encoding="utf-8")
        else:
            print(text)
        if errors:
            for e in errors:
                print(f"INVALID: {e}", file=sys.stderr)
            return 1
        return 0
    return 2  # pragma: no cover - argparse requires a subcommand


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
